### ISSUE TITLE
table 

### ISSUE THREAD

**Issue by mailtokarthik2003** [stefanuebe/html-table#1]
i want vaadin 7 like table in htmltable addon we have to change any idea...

**Comment by stefanuebe** [comment]
You could try to adapt my classes using the Elements addon: https://vaadin.com/directory/component/elements-add-on

**Comment by stefanuebe** [comment]
Ok, after re-reading the issue description: Unfortunately this is not a table as it was in Vaadin 7, but the integration of the html element `<table>`. So this is a markup element only and has no data related functionality or so, like the Vaadin 7 table had.

**Comment by TatuLund** [comment]
BeanTable is somewhat closer to Vaadin 7 Table by idea that it is populated by list of beans, but the API resembles more Grid than Table though https://vaadin.com/directory/component/beantable
